- hosts: 127.0.0.1
  connection: local
  tasks:
    # ZSH
    - name: install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      register: install_oh_my_zsh
      args:
        creates: ~/.oh-my-zsh
    - debug: msg="{{ install_oh_my_zsh.stdout }}"
    - name: check for .zshrc
      stat:
        path: ~/.zshrc
      register: zshrc_exists
    - name: check for .zprofile
      stat:
        path: ~/.zprofile
      register: zprofile_exists
    - name: add zshrc extras
      lineinfile:
        path: ~/.zshrc
        line: 'source "$HOME/.macos-env/resources/.zshrc_extra"'
      when: zshrc_exists.stat.exists == True
    - name: add sprofile extras
      lineinfile:
        path: ~/.zprofile
        line: 'source "$HOME/.macos-env/resources/.zshrc_extra"'
      when: zprofile_exists.stat.exists == True

    # Git stuff
    - name: Check for git user email
      register: git_user_email_present
      shell: git config user.email
      changed_when: git_user_email_present.rc == 1
      ignore_errors: True
    - name: Check for git user name
      register: git_user_name_present
      shell: git config user.name
      changed_when: git_user_name_present.rc == 1
      ignore_errors: True
    - name: Set git user email
      shell: git config --global user.email "{{ git_committer_email }}"
      when: git_user_email_present.rc == 1
    - name: Set git user name
      shell: git config --global user.name "{{ git_committer_name }}"
      when: git_user_name_present.rc == 1

    - name: Check for git excludes file
      register: git_user_excludesfile_present
      shell: git config core.excludesFile
      changed_when: git_user_excludesfile_present.rc == 1
      ignore_errors: True
    - name: Ensure global gitignore file
      copy:
        src: ./resources/.gitignore-global
        dest: ~/.gitignore-global
        force: no
      when: git_user_excludesfile_present.rc == 1
    - name: Set git excludesFile
      shell: git config --global core.excludesFile "~/.gitignore-global"
      when: git_user_excludesfile_present.rc == 1

    # Vim stuff
    - name: Add vimrc
      file:
        path: ~/.vimrc
        state: touch
    - name: Configure vimrc
      lineinfile:
        path: ~/.vimrc
        line: source ~/.macos-env/resources/.vimrc


    # Java
    - name: Add Jenv
      homebrew:
        name: jenv
        update_homebrew: yes
    - name: Tap brew cask
      community.general.homebrew_tap:
        name: homebrew/cask-versions
    - name: Add Temurin17
      homebrew_cask:
        name: temurin17
    - name: Install maven
      homebrew:
        name: maven


    # Node
    - name: Add FNM
      homebrew:
        name: fnm

    - name: Add Go
      homebrew:
        name: go

    # Misc
    - name: Add thefuck
      homebrew:
        name: thefuck
    - name: Add tree
      homebrew:
        name: tree
    - name: Add libpq
      homebrew:
        name: libpq
    - name: Add jq
      homebrew:
        name: jq
    - name: Add dbmate
      homebrew:
        name: dbmate
    - name: Add Docker
      homebrew_cask:
        name: docker
    - name: Add direnv
      homebrew:
        name: direnv
